#!/bin/bash
find . -maxdepth 1 -name '[[:alnum:]]*' -printf "%f\n" | sort -d --ignore-case | awk '{ORS = (NR == 1) ? ", " : ($0 == "." || $0 == "..") ? ", " : (/\/$/) ? ", " : "/"} 1' | sed 's/, $/\n/'
